stages:
  make_dataset:
    cmd: poetry run python src/make_dataset.py data/train.parquet
    deps:
      - src/make_dataset.py
    outs:
      - data/train.parquet

  format_dataset:
    cmd: poetry run python src/format_dataset.py data/train.parquet data/formatted_dataset.parquet
    deps:
      - src/format_dataset.py
      - data/train.parquet
    outs:
      - data/formatted_dataset.parquet
      - src/embedding/embedding.py

  embed_sentences:
    cmd: poetry run python src/embed_sentences.py data/formatted_dataset.parquet data/embeddings.parquet --dimension ${embedding.dimension} --modelname ${embedding.model_name} --limit ${embedding.limit}
    deps:
      - src/embed_sentences.py
      - data/formatted_dataset.parquet
    outs:
      - data/embeddings.parquet
