stages:

  generate_user_profiles:
    cmd: >-
      poetry run python src/generate_users.py
      --num_users=${num_users}
      --categories="technology,sports,music,art"
      data/users_with_sentences.parquet
    deps:
      - src/batch_processing/generate_users.py
    outs:
      - data/users_with_sentences.parquet

  embed_users:
    cmd: >-
      poetry run python src/embed_sentences.py
      data/users_with_sentences.parquet
      data/user_embeddings.parquet
    deps:
      - src/embedding_api/embed_sentences.py
      - data/users_with_sentences.parquet
    outs:
      - data/user_embeddings.parquet

  make_articles:
    cmd: >-
      poetry run python src/make_dataset.py
      data/train.parquet
    deps:
      - src/batch_processing/make_dataset.py
    outs:
      - data/train.parquet

  format_articles:
    cmd: >-
      poetry run python src/format_dataset.py
      data/train.parquet
      data/formatted_dataset.parquet
      --limit=${dataset.limit}
    deps:
      - src/batch_processing/format_dataset.py
      - data/train.parquet
    outs:
      - data/formatted_dataset.parquet

  embed_articles:
    cmd: >-
      poetry run python src/embed_sentences.py
      data/formatted_dataset.parquet
      data/article_embeddings.parquet
      --dimension=${embedding.dimension}
      --model_name=${embedding.model_name}
    deps:
      - src/embedding_api/embed_sentences.py
      - src/embedding_api/embedding.py
      - data/formatted_dataset.parquet
    outs:
      - data/article_embeddings.parquet

  generate_history:
    cmd: >-
      poetry run python src/generate_history.py
      data/article_embeddings.parquet
      data/user_embeddings.parquet
      data/user_history.parquet
      --max_views=${max_views}
    deps:
      - src/batch_processing/generate_history.py
      - data/article_embeddings.parquet
      - data/user_embeddings.parquet
    outs:
      - data/user_history.parquet

  load_users_to_elasticsearch:
    cmd: >-
      poetry run python src/load_to_elasticsearch.py
      --es_host=https://localhost:9200
      --index_name=user_sentences
      data/user_translation.parquet
      && echo `date` > data/load_users_timestamp.txt
    deps:
      - src/load_to_elasticsearch.py
      - data/user_translation.parquet
    outs:
      - data/load_users_timestamp.txt

  load_articles_to_elasticsearch:
    cmd: >-
      poetry run python src/load_to_elasticsearch.py
      --es_host=https://localhost:9200
      --index_name=article_data
      data/article_translation.parquet
      && echo `date` > data/load_articles_timestamp.txt
    deps:
      - src/load_to_elasticsearch.py
      - data/article_translation.parquet
    outs:
      - data/load_articles_timestamp.txt

  use_elasticsearch:
    cmd: >-
      echo use elasticsearch
      && echo `date` > data/use_elasticsearch.txt
    deps:
      - data/load_users_timestamp.txt
      - data/load_articles_timestamp.txt
    outs:
      - data/use_elasticsearch.txt

  make_user_translation:
    cmd: >-
      poetry run python src/make_user_translation.py
      data/user_embeddings.parquet
      data/user_translation.parquet
      models/two_tower_model.pth
    deps:
      - src/batch_processing/make_user_translation.py
      - data/user_embeddings.parquet
      - models/two_tower_model.pth
    outs:
      - data/user_translation.parquet

  make_article_translation:
    cmd: >-
      poetry run python src/make_article_translation.py
      data/article_embeddings.parquet
      data/article_translation.parquet
      models/two_tower_model.pth
    deps:
      - src/batch_processing/make_article_translation.py
      - data/article_embeddings.parquet
      - models/two_tower_model.pth
    outs:
      - data/article_translation.parquet

  learn_two_tower_model:
    cmd: >-
      poetry run python src/train_two_tower_model.py
      data/user_history.parquet
      models/two_tower_model.pth
      --epochs=${epochs}
      --patience=${patience}
    deps:
      - src/batch_processing/train_two_tower_model.py
      - data/user_history.parquet
      - src/two_tower_model.py
    outs:
      - models/two_tower_model.pth
