train:
  epochs: 20000
  patience: 500
dataset:
  limit: 1000
  num_users: 100
  max_views: 10
embedding:
  model_name: "intfloat/multilingual-e5-small"
  dimension: 384
elastic:
  index_suffix: "develop"
